-- JOIN 

-- vendas para cada vendedor
SELECT V.MATRICULA, V.NOME, NF.NUMERO
FROM TABELA_DE_VENDEDORES V INNER JOIN NOTAS_FISCAIS NF
ON V.MATRICULA = NF.MATRICULA;

-- conta a qtd de vendas que cada vendedor efetuou 
SELECT A.MATRICULA, A.NOME, COUNT(*)
FROM TABELA_DE_VENDEDORES A INNER JOIN NOTAS_FISCAIS B
ON A.MATRICULA = B.MATRICULA
GROUP BY A.MATRICULA, A.NOME;

-- EXERCICIO: Obtenha o faturamento anual da empresa. Leve em consideração 
-- que o valor financeiro das vendas consiste em multiplicar a quantidade pelo preço.
SELECT YEAR(B.DATA_VENDA) AS ANO, SUM(A.QUANTIDADE*A.PRECO) AS FATURAMENTO
FROM ITENS_NOTAS_FISCAIS A INNER JOIN NOTAS_FISCAIS B
ON A.NUMERO = B.NUMERO
GROUP BY year(DATA_VENDA);

-- nome e cpf dos clientes no cadastro que não compraram ainda
SELECT DISTINCT A.CPF, A.NOME, B.CPF
FROM TABELA_DE_CLIENTES A LEFT JOIN NOTAS_FISCAIS B
ON A.CPF = B.CPF
WHERE B.CPF IS NULL;


-- clientes e vendedores associados pelo bairro 
SELECT VENDEDOR.BAIRRO, VENDEDOR.NOME AS VENDEDOR, DE_FERIAS,
	CLIENTE.BAIRRO, CLIENTE.NOME AS CLIENTE
FROM TABELA_DE_VENDEDORES VENDEDOR FULL JOIN TABELA_DE_CLIENTES CLIENTE
ON CLIENTE.BAIRRO = VENDEDOR.BAIRRO; -- FULL JOIN não suportado pelo workbench

SELECT VENDEDOR.BAIRRO, VENDEDOR.NOME AS VENDEDOR, DE_FERIAS, CLIENTE.BAIRRO, CLIENTE.NOME AS CLIENTE
FROM TABELA_DE_VENDEDORES VENDEDOR LEFT JOIN TABELA_DE_CLIENTES CLIENTE ON CLIENTE.BAIRRO = VENDEDOR.BAIRRO
UNION 
SELECT VENDEDOR.BAIRRO, VENDEDOR.NOME AS VENDEDOR, DE_FERIAS, CLIENTE.BAIRRO, CLIENTE.NOME AS CLIENTE
FROM TABELA_DE_VENDEDORES VENDEDOR RIGHT JOIN TABELA_DE_CLIENTES CLIENTE ON CLIENTE.BAIRRO = VENDEDOR.BAIRRO;

-- retorna todos os bairros cadastrados em cliente e vendedores (exceto repetições)
SELECT DISTINCT BAIRRO, NOME, 'CLIENTE' AS TIPO
FROM TABELA_DE_CLIENTES 
UNION
SELECT DISTINCT BAIRRO, NOME, 'VENDEDOR' AS TIPO 
FROM TABELA_DE_VENDEDORES;