-- VISAO

-- vw_maiores_embalagens: maiores preços para aqueles maiores que 9
SELECT X.EMBALAGEM, X.MAIOR_PRECO FROM 
(SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO 
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM) X
WHERE X.MAIOR_PRECO > 9;

-- usando view
SELECT X.EMBALAGEM, X.MAIOR_PRECO 
FROM VW_MAIORES_EMBALAGENS X;

-- inner join com view
SELECT A.NOME_DO_PRODUTO, A.EMBALAGEM, A.PRECO_DE_LISTA, B.MAIOR_PRECO, 
	(A.PRECO_DE_LISTA / B.MAIOR_PRECO) * 100 AS PERCENTUAL
FROM TABELA_DE_PRODUTOS A INNER JOIN VW_MAIORES_EMBALAGENS B
ON A.EMBALAGEM = B.EMBALAGEM;VW_MAIORES_EMBALAGENS